### ISSUE TITLE
Invalid redirect_url 

### ISSUE THREAD

**Issue by vitthalmane** [blackboard/BBDN-LTI-Tool-Provider-Node#104]
@adgilmore @ewpreston @all I am running this code on localhost (https://127.0.0.1:3001) and i have also integrated with BB UEF + Proctoring Service (document url - https://docs.blackboard.com/lti/proctoring/ultra-proctoring-service-integration). I am getting **Invalid redirect_url: https://127.0.0.1:3001/lti13** after clicking on view assessment. 

I saw /login is also calling and after that it is redirecting to https://developer.blackboard.com/api/v1/gateway/oidcauth?....

Attaching Scrrenshot
![Screenshot from 2021-09-23 00-22-21](https://user-images.githubusercontent.com/52521093/134407126-21c18eb9-9578-4113-a4b6-f75c2161c62e.png)

**Comment by mark-b-kauffman** [comment]
The developer portal, developer.blackboard.com and the Learn system, whichever you are using, can not make http requests to 127.0.0.1 as that is not an FQDN that can be looked up via DNS. You will need to either (a) build your web application on a server that has an FQDN, like myserver.mycompany.com, and host it there, or (b) set up an ngrok solution as explained here: https://docs.blackboard.com/rest-apis/learn/uef/lti-to-uef-tutorial or here: https://docs.blackboard.com/lti/proctoring/ultra-proctoring-service-tutorials . You will have the ngrok set up to terminate SSL with a valid certificate and forward the request on to your server running at localhost/127.0.0.1. Once you have all that working, you will also need the URL you are redirecting to listed as one of the redirect URLs in your LTI registration on the developer portal. There is no issue with this github code. I see your team is a registered partner and has a Behind the Blackboard account. For further assistance, open a Behind the Blackboard ticket - after you get the FQDN forwarding working via ngrok or a similar service or have the tool hosted on a web server with a public FQDN and valid certificate that has been signed by a Certificate Authority. Thank you.
