### ISSUE TITLE
/tlcode request fails

### ISSUE THREAD

**Issue by shettyaditsathish** [blackboard/BBDN-LTI-Tool-Provider-Node#119]
I have set up AWS Blackboard Learn instance and did all the required settings.
I have registered the tool on both developer.blackboard.com and learn instance.
When the tool is launched it gets authenticated right but fails with {error: invalid_request, error_description: Application not registered with site}.

The code is using application key as client_id , I tried to modify it application id but no success.

Any help on the same will be greatly appreciated

**Comment by ewpreston** [comment]
It sounds to me you didn't register the app with the Learn instance. You must register as an LTI app as well as a REST application using the application ID

**Comment by shettyaditsathish** [comment]
I had not registered the application as a REST application, once that got done, I am now able to generate authorization code as well as access token.

Thanks! for the help
