### ISSUE TITLE
Redis Optional Note misleading and React-Router Warning

### ISSUE THREAD

**Issue by elmiguel** [blackboard/BBDN-LTI-Tool-Provider-Node#19]
Hey,

The readme documentation states that the Redis store is optional yet there is no check that skips this feature to allow it to continue and run. After installing Redis and re-running npm run start it continued and started the application.

Once the application is running and going the suggested urls provided in the console, the web console dumps an error: Warning: [react-router] Location "/lti" did not match any routes. The same goes for the /registration route as well.

`
// removed logging of installing redis...
[elmiguel@sector-zero BBDN-LTI-Tool-Provider-Node]$ sudo systemctl enable redis
Created symlink /etc/systemd/system/multi-user.target.wants/redis.service → /usr/lib/systemd/system/redis.service.
[elmiguel@sector-zero BBDN-LTI-Tool-Provider-Node]$ sudo systemctl start redis
[elmiguel@sector-zero BBDN-LTI-Tool-Provider-Node]$ npm run start

> lti-test-tool-provider@0.0.1 prestart /home/elmiguel/CodeProjects/blackboard/BBDN-LTI-Tool-Provider-Node
> npm install; npm run build-server; npm run build-public

> lti-test-tool-provider@0.0.1 postinstall /home/elmiguel/CodeProjects/blackboard/BBDN-LTI-Tool-Provider-Node
> bower install

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

> lti-test-tool-provider@0.0.1 build-server /home/elmiguel/CodeProjects/blackboard/BBDN-LTI-Tool-Provider-Node
> babel server/src -d server/lib --source-maps

server/src/app/action_log.js -> server/lib/app/action_log.js
server/src/app/content-item.js -> server/lib/app/content-item.js
server/src/app/eventstore.js -> server/lib/app/eventstore.js
server/src/app/hmac-sha1.js -> server/lib/app/hmac-sha1.js
server/src/app/lti-content-item.js -> server/lib/app/lti-content-item.js
server/src/app/lti.js -> server/lib/app/lti.js
server/src/app/redisutil.js -> server/lib/app/redisutil.js
server/src/app/registration.js -> server/lib/app/registration.js
server/src/app/routes.js -> server/lib/app/routes.js
server/src/app/tool_proxy_generator.js -> server/lib/app/tool_proxy_generator.js
server/src/app/utils.js -> server/lib/app/utils.js
server/src/common/restTypes.js -> server/lib/common/restTypes.js
server/src/config/config.js -> server/lib/config/config.js
server/src/server.js -> server/lib/server.js

> lti-test-tool-provider@0.0.1 build-public /home/elmiguel/CodeProjects/blackboard/BBDN-LTI-Tool-Provider-Node
> webpack --display-error-details

Hash: 4bd28949e9edd4216509
Version: webpack 2.7.0
Time: 3945ms
        Asset     Size  Chunks                    Chunk Names
    bundle.js  2.15 MB       0  [emitted]  [big]  main
bundle.js.map  2.23 MB       0  [emitted]         main
   [0] ./~/react/react.js 56 bytes {0} [built]
  [22] ./~/react-dom/index.js 59 bytes {0} [built]
  [61] ./~/react-bootstrap/es/index.js 4.85 kB {0} [built]
  [96] ./~/jquery/dist/jquery.js 268 kB {0} [built]
 [254] ./~/react-router/es/index.js 1.46 kB {0} [built]
 [255] ./public/src/app.js 2.04 kB {0} [built]
 [414] ./~/react-bootstrap/es/Form.js 1.91 kB {0} [built]
 [415] ./~/react-bootstrap/es/FormControl.js 3.47 kB {0} [built]
 [418] ./~/react-bootstrap/es/FormGroup.js 2.84 kB {0} [built]
 [419] ./~/react-bootstrap/es/HelpBlock.js 1.31 kB {0} [built]
 [420] ./~/react-bootstrap/es/Image.js 2.21 kB {0} [built]
 [421] ./~/react-bootstrap/es/InputGroup.js 1.58 kB {0} [built]
 [424] ./~/react-bootstrap/es/Jumbotron.js 1.61 kB {0} [built]
 [425] ./~/react-bootstrap/es/Label.js 1.97 kB {0} [built]
 [426] ./~/react-bootstrap/es/ListGroup.js 2.7 kB {0} [built]
    + 567 hidden modules

> lti-test-tool-provider@0.0.1 start /home/elmiguel/CodeProjects/blackboard/BBDN-LTI-Tool-Provider-Node
> node server/lib/server.js

{
  "provider_domain": "http://localhost",
  "provider_port": 3000,
  "redis_host": "localhost",
  "redis_port": 6379,
  "use_ssl": false
}
LTI 1 Tool Provider:  http://localhost:3000/lti
LTI 2 Registration URL:  http://localhost:3000/registration
LTI Content Item: http://localhost:3000/lti

`
![screenshot from 2017-07-27 17-30-45](https://user-images.githubusercontent.com/3842455/28693238-b8f17d9e-72f1-11e7-8ee8-f1d63c1d95c6.png)

**Comment by zaphodtx** [comment]
I ran into this issue as well.  I tried the docker versions and then ran into the same issues.

Also, the docker base image is no longer available or is in a private repo.  

> docker-compose up
Pulling redis (redis:)...
latest: Pulling from library/redis
4d0d76e05f3c: Pull complete
cfbf30a55ec9: Pull complete
82648e31640d: Pull complete
fb7ace35d550: Pull complete
497bf119bebf: Pull complete
89340f6074da: Pull complete
Digest: sha256:4aed8ea5a5fc4cf05c8d5341b4ae4a4f7c0f9301082a74f6f9a5f321140e0cd3
Status: Downloaded newer image for redis:latest
Pulling lti-tools (lti-tools:)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling lti-tools (lti-tools:)...
ERROR: pull access denied for lti-tools, repository does not exist or may require 'docker login'

**Comment by ewpreston** [comment]
I've made significant improvements to this application. I have not yet changed how redis works

Note the the URLs, such at /lti are NOT UI URLs, they are LTI launch URLs.

The docker base image we don't publish. Use docker build for that
