### ISSUE TITLE
Registration URL for the LTI 2.0

### ISSUE THREAD

**Issue by johandk89** [blackboard/BBDN-LTI-Tool-Provider-Node#49]
What URL should be used when registering an LTI 2.0 tool? 

![Screenshot 2019-09-30 at 16 26 13](https://user-images.githubusercontent.com/1677887/65887983-1a2d6a80-e39f-11e9-8910-e26f649f39c4.png)

**Comment by ewpreston** [comment]
Please don't use LTI 2.0. IMS Global has deprecated it, and we will no longer support it. We removed support for it from the Admin UI in a previous release.

LTI 1.3/Advantage is the correct route to go as it actually resolves security issues that persist in LTI 2.0.

**Comment by ewpreston** [comment]
See this page:

https://www.imsglobal.org/specs/ltiv2p0
