### ISSUE TITLE
Unable to add a Caliper provider

### ISSUE THREAD

**Issue by johandk89** [blackboard/BBDN-LTI-Tool-Provider-Node#54]
I'm trying to add a caliper provider to blackboard to use this tool, but I keep on getting this error: 

```
The specified resource was not found, or you do not have permission to access it.
```

Please also see my post on the blackboard forum 
https://community.blackboard.com/message/32063-send-analytics-to-blackboard

**Comment by shurrey** [comment]
So there are a couple of layers here. Technically speaking, yes, the current implementation of Caliper Providers is that you must launch from Learn via LTI, which passes you a registration URL. You then register against that URL and you are provided and endpoint that allows you to pass in Caliper events.
 
Currently, there is no way to access these events, however. The work was done a few years ago in concert with Kaltura to provide Kaltura usage reports in Learn.
 
That said, we are working over the next few quarters to make this easier for you to pass in your own data, as well as giving you access to it in conjunction with your other Blackboard telemetry data via Blackboard Data.
 
If you are actually a tool provider, then for the time being, it is best to just write directly to the customers event store.
