### ISSUE TITLE
Can I have a routes for Proctor request and response

### ISSUE THREAD

**Issue by veeresh-sd** [blackboard/BBDN-LTI-Tool-Provider-Node#72]
Can I have integrated Proctor endpoints with proper message_type according to the LTI standard
[](https://www.imsglobal.org/spec/proctoring/v1p0#h.a81u3sn00k84)

**Comment by veeresh-sd** [comment]
[](url)

**Comment by veeresh-sd** [comment]
I couldn't find a proper document in a Blackboard sigth.

**Comment by shurrey** [comment]
These have been added.
