### ISSUE TITLE
Webpack error

### ISSUE THREAD

**Issue by ginoescobar** [blackboard/BBDN-LTI-Tool-Provider-Node#99]
Hi, I was following the instructions and I came across the following error that I have not been able to fix.

> lti-test@0.0.1 build-public C:\Users\Hawk\Desktop\BBDN-LTI-Tool-Provider-Node
> webpack --display-error-details

>Hash: b09b31208681e789b1d4
>Version: webpack 4.46.0
>Time: 80ms
>Built at: 19-07-2021 18:12:20
>        Asset      Size  Chunks                   Chunk Names
    bundle.js  4.12 KiB    main  [emitted]        main
>bundle.js.map  3.53 KiB    main  [emitted] [dev]  main
>Entrypoint main = bundle.js bundle.js.map
>[./public/src/app.js] 356 bytes {main} [built] [failed] [1 error]

>ERROR in ./public/src/app.js 19:4
>Module parse failed: Unexpected token (19:4)
>You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
>|
>| ReactDOM.render(
>     <BrowserRouter>
>|       <Switch>
>|       <Route exact path="/setup" component={SetupView} />
>npm ERR! code ELIFECYCLE
>npm ERR! errno 2
>npm ERR! lti-test@0.0.1 build-public: `webpack --display-error-details`
>npm ERR! Exit status 2
>npm ERR!
>npm ERR! Failed at the lti-test@0.0.1 build-public script.
>npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

>npm ERR! A complete log of this run can be found in:
>npm ERR!     C:\Users\Hawk\AppData\Roaming\npm-cache\_logs\2021-07-19T22_12_21_228Z-debug.log

any way to fix it?

**Comment by ewpreston** [comment]
can you post the same thing you posted above as text? It will be easier to ask my Webpack experts about this.

I recommend you google this error; it's not one we've seen here before. What version of Node are you running? I've recently been running 14 or 16 with this project.

**Comment by ginoescobar** [comment]
> ¿Puedes publicar lo mismo que publicaste arriba como texto? Será más fácil preguntarles a mis expertos en Webpack sobre esto.
> 
> Te recomiendo que busques en Google este error; no es uno que hayamos visto aquí antes. ¿Qué versión de Node estás ejecutando? Recientemente he estado ejecutando 14 o 16 con este proyecto.

Ok, I have edited the post. I have also googled for a possible solution, but could not find it, writing this issue was my last resort.

my version of node:

`$ node -v
v14.17.1`

**Comment by ewpreston** [comment]
Hi, I just pushed a change to the webpack config that I think will fix your issue. Please confirm.

**Comment by ginoescobar** [comment]
> Hi, I just pushed a change to the webpack config that I think will fix your issue. Please confirm.

I confirm, problem solved. Thank you so much.
